import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Raleway } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const RalewaySans = Raleway({
	variable: "--font-Raleway-sans",
	subsets: ["latin"],
});

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={`${RalewaySans.variable} h-full antialiased`}>
			<body className="min-h-full flex flex-col">
				<div className="sticky top-0 z-999 w-full ||">
					<Header />
				</div>
				{children}
				<div className="">
					<Footer />
				</div>
				<div className=""></div>
			</body>
		</html>
	);
}
